#!/bin/bash

set -eu

VCGEN=/opt/vc/bin/vcgencmd
TEXTFILE=/var/lib/node_exporter/textfile_collector/raspberry-metrics.prom
TEMPFILE=$TEXTFILE.$$

mkdir -p /var/lib/node_exporter/textfile_collector/

TEMP=$(awk '{printf "%.2f", $1/1000}' /sys/class/thermal/thermal_zone0/temp)

if [ -z "$TEMP" ];
then
	echo "$NOW - Error: Value variable empty"
else
	echo "CPU_Temperature ${TEMP}" > $TEMPFILE

	mv $TEMPFILE $TEXTFILE
fi
